#+startup: content
* Home-Manager Configuration
[[https://circleci.com/gh/akirak/home.nix][https://circleci.com/gh/akirak/home.nix.svg?style=svg]]

This repository contains my user configuration files,
which are actually [[https://nixos.org/nix/][nix]] configuration files handled by [[https://github.com/rycee/home-manager][home-manager]].
If you are looking for a more modern way to manage /dotfiles/, this repository may or may not be an example.
However, a better example will be John Wiegley's [[https://github.com/jwiegley/nix-config][nix-config]] repository.
** Table of contents                                              :noexport:
:PROPERTIES:
:TOC:      siblings
:END:
-  [[#prerequisites][Prerequisites]]
-  [[#installation-and-usage][Installation and usage]]
  -  [[#initial-installation][Initial installation]]
    -  [[#bootstrapping][Bootstrapping]]
    -  [[#installation][Installation]]

** Prerequisites
This configuration should run on Linux operating systems.
** Installation and usage
*** Initial installation
**** Bootstrapping
You can install this configuration on any Linux machine without any dependencies:

#+begin_src shell
curl https://raw.githubusercontent.com/akirak/home.nix/master/bootstrap.sh | sh
#+end_src

It installs dependencies, clones the repository in =~/home.nix=, and runs all jobs required for installation. It also installs [[https://github.com/akirak/emacs.d][my Emacs configuration]] if =~/.emacs.d= does not exist.

Alternatively, you can clone this repository to anywhere and run

#+begin_src shell
./bootstrap.sh
#+end_src
**** Installation
Run

#+begin_src shell
make all
#+end_src

to install all the components.
** Meta                                                           :noexport:
:PROPERTIES:
:TOC:      ignore
:END:
# Local Variables:
# before-save-hook: org-make-toc
# org-id-link-to-org-use-id: nil
# org-src-preserve-indentation: t
# End:
