version: 2
jobs:
  build:
    environment:
      TERM: dumb
      NIX_PATH: /root/.nix-defexpr/channels
      HOME_MANAGER_CONFIG: /root/nix/home.nix
    docker:
      - image: akirak/nixmacs-bootstrap
    working_directory:
      ~/nix
    steps:
      - checkout
      - run: nix-channel --update
      - run: nix-shell '<home-manager>' -A install
      - run: home-manager switch
      - run: make -C test -f test.mk all
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
