#!/bin/sh

# Set the default shell to zsh.

# This script works on Nix on Chrome OS and other platforms.
#
# Run this script as a normal user.

if [ "${SKIP_CHSH}" = 1 ]; then
    echo "Skipped chsh"
    exit 0
fi

set -e

expected="$(command -v zsh)"

current="$(getent passwd $USER | cut -d: -f7)"

if [ "$current" = "$expected" ]; then
    echo "The shell has been already set to zsh."
    echo "Quitting"
    exit 0
fi

if ! grep -qxF "$expected" /etc/shells; then
    echo "Add $expected to /etc/shells"
    sudo sed "\$ a $expected" /etc/shells
fi
chsh -s "$expected"
