#!/usr/bin/env bash

ource_if_existing() {
    for src; do
        if [ -e "$src" ]; then
            echo "$(basename \"$0\"): Sourcing $src..."
            . "$src"
        fi
    done
}

if [[ -v HOME ]] && [[ -v USER ]]; then
    source_if_existing "$HOME/.nix-profile/etc/profile.d/nix.sh"
    source_if_existing "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
else
    echo "\$HOME and/or \$USER is not defined. This can go wrong."
fi

exec "$@"
