#!/bin/bash

# Start Xephyr with the correct DPI

if [ $# -eq 0 ]; then
    echo "Please specify the display as the first argument." >&2
    exit 1
fi

dimensions=$(xdpyinfo -display "$DISPLAY" | grep dimensions:)
if [[ "$dimensions" =~ ([[:digit:]]+)x([[:digit:]]+)\ pixels ]]; then
    widthInPixels=${BASH_REMATCH[1]}
    heightInPixels=${BASH_REMATCH[2]}
else
    echo "Dimensions mismatch (1)" >&2
    exit 1
fi
if [[ "$dimensions" =~ ([[:digit:]]+)x([[:digit:]]+)\ millimeters ]]; then
    widthInMm=${BASH_REMATCH[1]}
    heightInMm=${BASH_REMATCH[2]}
else
    echo "Dimensions mismatch (2)" >&2
    exit 1
fi

spec="${widthInPixels}/${widthInMm}x${heightInPixels}/${heightInMm}"
echo "Creating a new display $1 with screen $spec"
exec Xephyr "$1" -screen "$spec" -resizeable

# resolution=$(xdpyinfo -display "$DISPLAY" | grep resolution:)
# if [[ "$resolution" =~ ([[:digit:]]+)x[[:digit:]]+ ]]; then
#     dpi=${BASH_REMATCH[1]}
#     exec Xephyr "$1" -dpi $dpi -fullscreen -resizeable
# else
#     exit 1
# fi
